Changed to get session id
Black0nion/BlackOnionDashBoard pull request #10
Opened 2023-04-08 16:35 UTC by RealYusufIsmail

2023-04-10 22:31 UTC, RealYusufIsmail commented on src/utils/api.ts
> +        return new GuildImpl(json.id, json)
Have a look it. Might need to add back

2023-04-11 02:50 UTC, RealYusufIsmail commented on src/utils/api.ts
> +        return new GuildImpl(json.id, json)
Nvm

2023-04-12 12:57 UTC, SIMULATAN requested changes
Some minor changes are required, other than those comments, LGTM!

2023-04-12 12:57 UTC, SIMULATAN commented on src/App.tsx
> +    const accesToken = getCookie("access_token")
Typo: change to "accessToken"

2023-04-12 12:57 UTC, SIMULATAN commented on src/App.tsx
> +    //if acccess token exists in cookies, redirect to dashboard
Typo: change to "access"

2023-04-12 12:57 UTC, SIMULATAN commented on README.md
> +  "auth_api_url": "",
`auth_api_url` was changed to `bot_api`

2023-04-12 12:57 UTC, SIMULATAN commented on README.md
>    "client_secret": "",
To be removed, the secret is only required in the backend.
In fact, when it's supplied, the client will get it and compromise our OAuth2

2023-04-12 12:57 UTC, SIMULATAN commented on src/pages/onboarding/Callback.tsx
> +            //todo : change sent text to include expiry time
Implement this
The JWT token can be decoded to get the expiration time.
Refreshing that token is out of scope for this PR.

2023-04-12 17:37 UTC, RealYusufIsmail commented on src/pages/onboarding/Callback.tsx
> +            //todo : change sent text to include expiry time
What do you send, so i know what to decode

2023-04-12 21:36 UTC, SIMULATAN commented on src/pages/onboarding/Callback.tsx
> +            //todo : change sent text to include expiry time
One example token issued for my user:
```
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODE5Mzk4OTUsImlzcyI6IkJsYWNrT25pb24tQm90Iiwic3ViIjoiNTA1NzEzNzYwMTI0NjY1ODY3In0.QN4V7ueA4lMItx2PJEeIJyBYgBRoFK5maGUj5KAN7fXSYmqoHDbKFHiVCS2vR6IsV3V1FRSXek-_ZdfGfyGJoA
```
and before anyone asks, no, you can't use that token anywhere.

Anyway, using [jwt.io](https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODE5Mzk4OTUsImlzcyI6IkJsYWNrT25pb24tQm90Iiwic3ViIjoiNTA1NzEzNzYwMTI0NjY1ODY3In0.QN4V7ueA4lMItx2PJEeIJyBYgBRoFK5maGUj5KAN7fXSYmqoHDbKFHiVCS2vR6IsV3V1FRSXek-_ZdfGfyGJoA), you can check the token and see the information stored in it. According to the JWT specification, you can literally just Base64 decode the 2nd part of the token to get the JSON stored in it. In there, you can see the `exp` date which is the unix timestamp (seconds) at which the token expires.

In the future, you'll have to refresh that token every `MAX_LIFETIME / 2`. In this case, the lifetime is 7 days, as seen [here](https://github.com/Black0nion/BlackOnion-Bot/blob/c0a628e20bb38962b43f2b8e6cd035b6f88862e6/src/main/java/com/github/black0nion/blackonionbot/utils/AuthUtils.java#L28), so you'll have to refresh the token roughly every 4-5 days, but as I said, that's for another PR.

TL;DR: base64 decode the 2nd out of 3 parts of the token the backend provides you and get the `exp` json field of it to check at which unix epoch timestamp it expires.

2023-04-13 12:04 UTC, SIMULATAN approved these changes
LGTM!

2023-04-13 12:04 UTC, SIMULATAN commented on src/pages/onboarding/Callback.tsx
> +            setCookie("access_token", accessToken, {path: "/", expires: formattedExpiryTime});
Oh wow, that exists? Great!

2023-04-13 13:22 UTC, RealYusufIsmail commented on src/pages/onboarding/Callback.tsx
> +            setCookie("access_token", accessToken, {path: "/", expires: formattedExpiryTime});
No problem

2023-04-13 13:23 UTC, merged